### ISSUE TITLE
DHB Dataset

### ISSUE THREAD

**Issue by zhouzhouha** [ispc-lab/NeuralPCI#1]
Hello, thanks for the introduction, but  I don't understand the description in DHB dataset, each frame has 1024 points. what does this mean?

**Comment by dyfcalid** [comment]
We follow the DHB dataset setup in [IDEA-Net](https://arxiv.org/abs/2203.11590) and each sample in the point cloud sequence is uniformly downsampled to a fixed 1024 points.
