### ISSUE TITLE
Visualization Code

### ISSUE THREAD

**Issue by jiangchaokang** [ispc-lab/NeuralPCI#3]
Your paper features excellent visualization effects. Could you provide the image and video visualization codes related to the paper? Access to the visualization code would be extremely helpful to me. I am looking forward to your reply. @dyfcalid

**Comment by dyfcalid** [comment]
We use `mayavi` for visualization (also can be done by `open3d`). There's no special technique and you can follow your own needs. As for the video demo, we save the rendered images, convert them into gif/mp4 and then make it in `Adobe Premiere`. So there is no straightforward code available. If you still have specific questions about details, go ahead and contact me.


An example for `mayavi`:
```python
import mayavi
def viz_mayavi(points, vals="distance", colormap='summer', azi=0, zen=0):
    x=points[:, 0]
    y=points[:, 1]
    z=points[:, 2]
    d=np.sqrt(x**2+y**2)

    if vals == "height":
        col = z
    else:
        col = d

    fig = mayavi.mlab.figure(bgcolor=(1, 1, 1), size=(600, 800))
    vis = mayavi.mlab.points3d(x, y, z,
                         col,
                         mode="sphere",
                         colormap=colormap,
                         figure=fig,
                         scale_factor=0.04,
                         )
    vis.glyph.scale_mode = 'data_scaling_off'
    vis.glyph.color_mode = 'color_by_scalar'
    mayavi.mlab.view(azi, zen, distance=3.5)
    mayavi.mlab.show()
```
