### ISSUE TITLE
Python version 3.9 and Open3D version 0.9.0 are not compatible.

### ISSUE THREAD

**Issue by Fiiiiifi** [ispc-lab/NeuralPCI#5]
Hi，Thanks for your wonderful work！

**Comment by Fiiiiifi** [comment]
When I try to follow the instructions in the README to set up the environment, I am unable to install the Open3D library and encounter error messages：
```
Encountered problems while solving:
  - package open3d-0.9.0.0-py27_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ open3d 0.9.0  is installable with the potential options
│  ├─ open3d 0.9.0.0 would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ open3d 0.9.0.0 would require
│  │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  ├─ open3d 0.9.0.0 would require
│  │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  └─ open3d 0.9.0.0 would require
│     └─ python >=3.5,<3.6.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.9.* , which conflicts with any installable versions previously reported.

bash: __vsc_prompt_cmd_original: command not found
```
I'm running in
Ubuntu 20.04,
CUDA version 11.3 
Python version 3.9.19. 
I really hope you can help me with this issue.

**Comment by dyfcalid** [comment]
Maybe you can install a higher version of open3d to fix it.
Or try the latest one using `pip install open3d`

**Comment by Fiiiiifi** [comment]
> Maybe you can install a higher version of open3d to fix it. Or try the latest one using `pip install open3d`

Thanks!!!! I've solved the problem by installing the version of 0.18.0
